apiVersion: v1
kind: Service
metadata: # kpt-merge: ves-system/ver-nodeport-ver-0
  name: ver-loadbalancer
  namespace: ves-system
  labels:
    app: ver
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|ves-system|ver-nodeport-ver-0'
spec:
  type: LoadBalancer
  ports:
    - name: "ver-ike"
      protocol: UDP
      port: 4500
      targetPort: 4500
  selector:
    app: ver
