apiVersion: v1
kind: Service
metadata: # kpt-merge: ves-system/ver-nodeport-ver-0
  name: ver-nodeport-ver-0
  namespace: ves-system
  labels:
    app: ver
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|ves-system|ver-nodeport-ver-0'
    community.f5.com/purpose: site-mesh-gateway
    community.f5.com/source: github.com/memes/f5xc-gke-sitemesh
spec:
  type: NodePort
  ports:
    - name: "ver-ike"
      protocol: UDP
      port: 4500
      targetPort: 4500
      nodePort: 30500
  selector:
    statefulset.kubernetes.io/pod-name: ver-0
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: ves-system/ver-nodeport-ver-1
  name: ver-nodeport-ver-1
  namespace: ves-system
  labels:
    app: ver
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|ves-system|ver-nodeport-ver-1'
    community.f5.com/purpose: site-mesh-gateway
    community.f5.com/source: github.com/memes/f5xc-gke-sitemesh
spec:
  type: NodePort
  ports:
    - name: "ver-ike"
      protocol: UDP
      port: 4500
      targetPort: 4500
      nodePort: 30501
  selector:
    statefulset.kubernetes.io/pod-name: ver-1
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: ves-system/ver-nodeport-ver-2
  name: ver-nodeport-ver-2
  namespace: ves-system
  labels:
    app: ver
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|ves-system|ver-nodeport-ver-2'
    community.f5.com/purpose: site-mesh-gateway
    community.f5.com/source: github.com/memes/f5xc-gke-sitemesh
spec:
  type: NodePort
  ports:
    - name: "ver-ike"
      protocol: UDP
      port: 4500
      targetPort: 4500
      nodePort: 30502
  selector:
    statefulset.kubernetes.io/pod-name: ver-2
