# spell-checker: disable
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

commonAnnotations:
  community.f5.com/f5xc-gke-site-mesh-purpose: origin-pool
  community.f5.com/f5xc-gke-site-mesh-source: github.com/memes/f5xc-gke-sitemesh
