# TODO @memes remove is not a golang project
# spell-checker: disable
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Install cosign
        if: ${{ success() }}
        uses: sigstore/cosign-installer@v2.8.1
      - name: Install syft
        if: ${{ success() }}
        uses: anchore/sbom-action/download-syft@v0.13.1
      - id: docker-login
        name: Login to Docker hub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - id: ghcr-login
        name: Login to GitHub Container Registry
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Go Report update
        if: ${{ success() }}
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://goreportcard.com/checks'
          method: 'POST'
          contentType: 'application/x-www-form-urlencoded'
          data: 'repo=github.com/${{ github.repository }}'
          preventFailureOnNoResponse: 'true'
